var compProp={
  "main":{
    "properties":{
      "attention":1,
      "interactivity":0,
      "processingReq":0.3,
      "customization":0,
      "broadcastReq":1
    },
    "dimensions":{
      "xmin":16,
      "ymin":9,
      "xmax":16,
      "ymax":9
    }
  },
  "video":{
    "properties":{
      "attention":0.7,
      "interactivity":0.3,
      "processingReq":0.9,
      "customization":0.2,
      "broadcastReq":0
    },
    "dimensions":{
      "xmin":16,
      "ymin":9,
      "xmax":16,
      "ymax":9
    }
  },
  "banner":{
    "properties":{
      "attention":0.8,
      "interactivity":0.2,
      "processingReq":0.1,
      "customization":0,
      "broadcastReq":0
    },
    "dimensions":{
      "xmin":16,
      "ymin":9,
      "xmax":16,
      "ymax":9
    }
  },
  "staticData":{
    "properties":{
      "attention":0.6,
      "interactivity":0.2,
      "processingReq":0.2,
      "customization":0,
      "broadcastReq":0
    },
    "dimensions":{
      "xmin":16,
      "ymin":9,
      "xmax":16,
      "ymax":9
    }
  },
  "dynamicData":{
    "properties":{
      "attention":0.6,
      "interactivity":1,
      "processingReq":0.3,
      "customization":1,
      "broadcastReq":0
    },
    "dimensions":{
      "xmin":16,
      "ymin":9,
      "xmax":16,
      "ymax":9
    }
  },
  "social":{
    "properties":{
      "attention":0.3,
      "interactivity":1,
      "processingReq":0.3,
      "customization":1,
      "broadcastReq":0
    },
    "dimensions":{
      "xmin":16,
      "ymin":9,
      "xmax":16,
      "ymax":9
    }
  },
  "UGC":{
    "properties":{
      "attention":0.3,
      "interactivity":1,
      "processingReq":0.6,
      "customization":1,
      "broadcastReq":0
    },
    "dimensions":{
      "xmin":16,
      "ymin":9,
      "xmax":16,
      "ymax":9
    }
  },
  "advertisement":{
    "properties":{
      "attention":0.2,
      "interactivity":0,
      "processingReq":0.9,
      "customization":0,
      "broadcastReq":0
    },
    "dimensions":{
      "xmin":16,
      "ymin":9,
      "xmax":16,
      "ymax":9
    }
  }
};
var devProp={
  "mobile":{
    "properties":{
      "screensize":0.2,
      "inputCapabilities":0.7,
      "processingCap":0.7,
      "privacy":1,
      "broadcastCap":0
    },
    "dimensions":{
      "xp":16,
      "yp":9,
      "cut_pip":1,
      "cut_split":2,
      "exp_carousel":0.5
    }
  },
  "tablet":{
    "properties":{
      "screensize":0.5,
      "inputCapabilities":0.8,
      "processingCap":0.8,
      "privacy":0.8,
      "broadcastCap":0
    },
    "dimensions":{
      "xp":16,
      "yp":9,
      "cut_pip":5,
      "cut_split":6,
      "exp_carousel":0.5
    }
  },
  "computer":{
    "properties":{
      "screensize":0.7,
      "inputCapabilities":1,
      "processingCap":1,
      "privacy":0.5,
      "broadcastCap":0
    },
    "dimensions":{
      "xp":16,
      "yp":9,
      "cut_pip":8,
      "cut_split":9,
      "exp_carousel":0.5
    }
  },
  "smartTv":{
    "properties":{
      "screensize":1,
      "inputCapabilities":0.2,
      "processingCap":0.2,
      "privacy":0.1,
      "broadcastCap":1
    },
    "dimensions":{
      "xp":16,
      "yp":9,
      "cut_pip":8,
      "cut_split":9,
      "exp_carousel":0.7
    }
  }
};
var affinityMat=[[1,0,0,0.1,0,0,0],[0.1,1,0.5,1,0,0,0],[0.3,0.1,1,0,0,0,0],[0.1,0.5,0,1,0,0,0],[0,0,0,0,1,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]];

var criteria=["A","S","E","D"];
var criteriaVal=[0.8,0.2,3,1];
